import type { CompetitionFormatDefinition, CompetitionFormatSlug, SportDefinition, SportFeature } from './types'

export const COMPETITION_FORMATS: Record<CompetitionFormatSlug, CompetitionFormatDefinition> = {
  league: {
    slug: 'league',
    name: 'Liga',
    description: 'Tabla acumulada por puntos, ideal para temporadas regulares.',
    minParticipants: 2,
    recommendedParticipants: '6 a 24',
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['clock', 'tieBreakers', 'ranking'],
    defaultFixture: 'roundRobin',
  },
  'round-robin': {
    slug: 'round-robin',
    name: 'Todos contra todos',
    description: 'Cada participante enfrenta a todos los demás una o más veces.',
    minParticipants: 2,
    recommendedParticipants: '4 a 20',
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['tieBreakers', 'ranking'],
    defaultFixture: 'roundRobin',
  },
  'single-elimination': {
    slug: 'single-elimination',
    name: 'Eliminación simple',
    description: 'Bracket directo: quien pierde queda eliminado.',
    minParticipants: 2,
    recommendedParticipants: '4 a 128',
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['bracket', 'playoffs'],
    defaultFixture: 'bracket',
  },
  'double-elimination': {
    slug: 'double-elimination',
    name: 'Eliminación doble',
    description: 'Bracket con winners y losers bracket.',
    minParticipants: 4,
    recommendedParticipants: '8 a 64',
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['bracket', 'playoffs', 'grand-final'],
    defaultFixture: 'bracket',
  },
  swiss: {
    slug: 'swiss',
    name: 'Sistema suizo',
    description: 'Rondas pareadas por rendimiento, sin eliminar participantes.',
    minParticipants: 4,
    recommendedParticipants: '8 a 256',
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['ranking', 'tieBreakers'],
    defaultFixture: 'manual',
  },
  'groups-playoffs': {
    slug: 'groups-playoffs',
    name: 'Grupos + playoff',
    description: 'Fase de grupos clasificatoria seguida de llaves finales.',
    minParticipants: 4,
    recommendedParticipants: '8 a 64',
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['groups', 'playoffs', 'bracket', 'classification'],
    defaultFixture: 'groupsPlayoffs',
  },
  ladder: {
    slug: 'ladder',
    name: 'Ladder',
    description: 'Ranking vivo con desafíos entre posiciones.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['ranking'],
    defaultFixture: 'manual',
  },
  'king-of-the-hill': {
    slug: 'king-of-the-hill',
    name: 'King of the hill',
    description: 'El ganador permanece y recibe nuevos desafiantes.',
    minParticipants: 3,
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['ranking'],
    defaultFixture: 'manual',
  },
  arena: {
    slug: 'arena',
    name: 'Arena',
    description: 'Sesiones abiertas con cola de partidas y ranking por puntos.',
    minParticipants: 4,
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['ranking', 'clock'],
    defaultFixture: 'manual',
  },
  'battle-royale': {
    slug: 'battle-royale',
    name: 'Battle royale',
    description: 'Múltiples participantes compiten en una misma partida por colocación.',
    minParticipants: 8,
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['ranking', 'classification'],
    defaultFixture: 'classification',
  },
  'time-trial': {
    slug: 'time-trial',
    name: 'Clasificación por tiempo',
    description: 'Gana quien registre el menor tiempo acumulado.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['classification', 'ranking'],
    defaultFixture: 'classification',
  },
  'points-classification': {
    slug: 'points-classification',
    name: 'Clasificación por puntos',
    description: 'Ranking por puntos acumulados en eventos o pruebas.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['classification', 'ranking'],
    defaultFixture: 'classification',
  },
  heats: {
    slug: 'heats',
    name: 'Heats',
    description: 'Mangas clasificatorias con avance por marcas o posiciones.',
    minParticipants: 4,
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['heats', 'classification', 'ranking'],
    defaultFixture: 'heats',
  },
  stages: {
    slug: 'stages',
    name: 'Stages',
    description: 'Competencia por etapas con clasificación acumulada.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['classification', 'ranking'],
    defaultFixture: 'classification',
  },
  pools: {
    slug: 'pools',
    name: 'Pools',
    description: 'Grupos pequeños con clasificación interna.',
    minParticipants: 4,
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['groups', 'classification'],
    defaultFixture: 'groupsPlayoffs',
  },
  conference: {
    slug: 'conference',
    name: 'Conferencias',
    description: 'Temporada separada por conferencias con playoff posterior.',
    minParticipants: 8,
    supportedParticipantTypes: ['team'],
    features: ['groups', 'playoffs', 'series'],
    defaultFixture: 'groupsPlayoffs',
  },
  split: {
    slug: 'split',
    name: 'Split',
    description: 'Temporadas cortas con ranking y finales.',
    minParticipants: 4,
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['ranking', 'playoffs'],
    defaultFixture: 'groupsPlayoffs',
  },
  'grand-final': {
    slug: 'grand-final',
    name: 'Grand final',
    description: 'Final especial luego de una fase clasificatoria.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['playoffs', 'bracket'],
    defaultFixture: 'bracket',
  },
  bo1: {
    slug: 'bo1',
    name: 'BO1',
    description: 'Serie al mejor de 1.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['series'],
    defaultFixture: 'series',
    bestOf: 1,
  },
  bo3: {
    slug: 'bo3',
    name: 'BO3',
    description: 'Serie al mejor de 3.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['series'],
    defaultFixture: 'series',
    bestOf: 3,
  },
  bo5: {
    slug: 'bo5',
    name: 'BO5',
    description: 'Serie al mejor de 5.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['series'],
    defaultFixture: 'series',
    bestOf: 5,
  },
  bo7: {
    slug: 'bo7',
    name: 'BO7',
    description: 'Serie al mejor de 7.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'doubles', 'team', 'mixed'],
    features: ['series'],
    defaultFixture: 'series',
    bestOf: 7,
  },
  'home-away': {
    slug: 'home-away',
    name: 'Ida y vuelta',
    description: 'Dos partidos por cruce, alternando localía.',
    minParticipants: 2,
    supportedParticipantTypes: ['team', 'doubles', 'individual'],
    features: ['homeAway', 'aggregate'],
    defaultFixture: 'roundRobin',
  },
  'aggregate-score': {
    slug: 'aggregate-score',
    name: 'Marcador global',
    description: 'Clasificación por suma de resultados en una serie.',
    minParticipants: 2,
    supportedParticipantTypes: ['team', 'doubles', 'individual'],
    features: ['aggregate', 'series'],
    defaultFixture: 'series',
  },
  olympic: {
    slug: 'olympic',
    name: 'Sistema olímpico',
    description: 'Clasificación, repechaje y finales según disciplina.',
    minParticipants: 4,
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['heats', 'classification', 'playoffs'],
    defaultFixture: 'heats',
  },
  fifa: {
    slug: 'fifa',
    name: 'Formato FIFA',
    description: 'Grupos, eliminación y criterios FIFA.',
    minParticipants: 8,
    supportedParticipantTypes: ['team'],
    features: ['groups', 'playoffs', 'tieBreakers'],
    defaultFixture: 'groupsPlayoffs',
  },
  atp: {
    slug: 'atp',
    name: 'Formato ATP',
    description: 'Cuadro de tenis con seeds y partidos por sets.',
    minParticipants: 4,
    supportedParticipantTypes: ['individual', 'doubles'],
    features: ['sets', 'bracket', 'ranking'],
    defaultFixture: 'bracket',
  },
  'davis-cup': {
    slug: 'davis-cup',
    name: 'Formato Davis',
    description: 'Series por equipos con singles y dobles.',
    minParticipants: 2,
    supportedParticipantTypes: ['team'],
    features: ['series', 'sets'],
    defaultFixture: 'series',
  },
  nba: {
    slug: 'nba',
    name: 'Formato NBA',
    description: 'Conferencias, temporada regular y series BO7.',
    minParticipants: 8,
    supportedParticipantTypes: ['team'],
    features: ['conference', 'playoffs', 'series'],
    defaultFixture: 'groupsPlayoffs',
    bestOf: 7,
  },
  worlds: {
    slug: 'worlds',
    name: 'Formato Worlds',
    description: 'Etapas, grupos, suizo o playoffs según temporada.',
    minParticipants: 8,
    supportedParticipantTypes: ['team'],
    features: ['groups', 'playoffs', 'series'],
    defaultFixture: 'groupsPlayoffs',
  },
  'champions-league': {
    slug: 'champions-league',
    name: 'Formato Champions League',
    description: 'Fase liga/grupos y llaves con ida/vuelta.',
    minParticipants: 8,
    supportedParticipantTypes: ['team'],
    features: ['groups', 'homeAway', 'aggregate', 'playoffs'],
    defaultFixture: 'groupsPlayoffs',
  },
  'world-cup': {
    slug: 'world-cup',
    name: 'Formato Copa del Mundo',
    description: 'Grupos y eliminación directa con reglas de clasificación.',
    minParticipants: 8,
    supportedParticipantTypes: ['team'],
    features: ['groups', 'playoffs', 'tieBreakers'],
    defaultFixture: 'groupsPlayoffs',
  },
  ufc: {
    slug: 'ufc',
    name: 'Formato UFC',
    description: 'Cartelera de combates con rounds y decisión/juez.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual'],
    features: ['rounds'],
    defaultFixture: 'manual',
  },
  crossfit: {
    slug: 'crossfit',
    name: 'Formato CrossFit',
    description: 'Eventos con ranking por puntos, reps, cargas o tiempos.',
    minParticipants: 2,
    supportedParticipantTypes: ['individual', 'team', 'mixed'],
    features: ['classification', 'ranking'],
    defaultFixture: 'classification',
  },
}

const teamBallMetrics = [
  { key: 'goalsFor', label: 'Goles a favor', type: 'number', scope: 'team' },
  { key: 'goalsAgainst', label: 'Goles en contra', type: 'number', scope: 'team' },
  { key: 'goalDifference', label: 'Diferencia', type: 'number', scope: 'team' },
] as const

const pointMetrics = [
  { key: 'pointsFor', label: 'Puntos a favor', type: 'number', scope: 'team' },
  { key: 'pointsAgainst', label: 'Puntos en contra', type: 'number', scope: 'team' },
  { key: 'pointDifference', label: 'Diferencia', type: 'number', scope: 'team' },
] as const

const defaultSupports: Record<SportFeature, boolean> = {
  playoffs: false,
  groups: false,
  homeAway: false,
  series: false,
  sets: false,
  rounds: false,
  heats: false,
  clock: false,
  ranking: true,
  classification: false,
  overtime: false,
  tieBreakers: true,
  aggregate: false,
  bracket: false,
  conference: false,
  'grand-final': false,
}

function sport(input: Omit<SportDefinition, 'supports'> & { supports?: Partial<SportDefinition['supports']> }): SportDefinition {
  return {
    ...input,
    supports: { ...defaultSupports, ...input.supports },
  }
}

export const SPORTS: SportDefinition[] = [
  sport({
    name: 'Fútbol',
    slug: 'football',
    type: ['team'],
    participantCount: { min: 2, default: 11, max: 30, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'home-away', 'aggregate-score', 'fifa', 'champions-league', 'world-cup'],
    scoring: { unit: 'goals', win: 3, draw: 1, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['points', 'goalDifference', 'goalsFor', 'headToHead', 'fairPlay'] },
    matchStructure: { playersPerSide: 11, rosterMin: 7, rosterMax: 23, periods: 2, periodLabel: 'tiempo', periodMinutes: 45 },
    metrics: [...teamBallMetrics],
    ruleFields: [
      { key: 'halves', label: 'Tiempos', type: 'number', defaultValue: 2, min: 1, max: 4 },
      { key: 'minutesPerHalf', label: 'Minutos por tiempo', type: 'number', defaultValue: 45, min: 5, max: 60 },
      { key: 'allowExtraTime', label: 'Permitir alargue', type: 'boolean', defaultValue: false },
      { key: 'allowPenalties', label: 'Definir por penales', type: 'boolean', defaultValue: true },
    ],
    standings: { columns: ['PJ', 'G', 'E', 'P', 'GF', 'GC', 'DIF', 'PTS'], sort: ['points', 'goalDifference', 'goalsFor'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Goles', participantLabel: 'Equipo', matchLabel: 'Partido', tableLabel: 'Tabla de posiciones', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, homeAway: true, aggregate: true, clock: true, overtime: true, bracket: true },
    presets: [
      { slug: 'local-league', name: 'Liga local', formatSlug: 'league', rules: { halves: 2, minutesPerHalf: 45, allowExtraTime: false, allowPenalties: false } },
      { slug: 'world-cup', name: 'Copa del Mundo', formatSlug: 'world-cup', rules: { groups: 8, advancePerGroup: 2, allowExtraTime: true, allowPenalties: true } },
    ],
  }),
  sport({
    name: 'Futsal',
    slug: 'futsal',
    type: ['team'],
    participantCount: { min: 2, default: 5, max: 14, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'home-away', 'fifa'],
    scoring: { unit: 'goals', win: 3, draw: 1, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['points', 'goalDifference', 'goalsFor', 'headToHead'] },
    matchStructure: { playersPerSide: 5, rosterMin: 5, rosterMax: 14, periods: 2, periodLabel: 'tiempo', periodMinutes: 20 },
    metrics: [...teamBallMetrics, { key: 'fouls', label: 'Faltas acumuladas', type: 'number', scope: 'team' }],
    ruleFields: [
      { key: 'minutesPerHalf', label: 'Minutos por tiempo', type: 'number', defaultValue: 20, min: 5, max: 30 },
      { key: 'accumulatedFouls', label: 'Faltas acumuladas', type: 'boolean', defaultValue: true },
    ],
    standings: { columns: ['PJ', 'G', 'E', 'P', 'GF', 'GC', 'DIF', 'PTS'], sort: ['points', 'goalDifference', 'goalsFor'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Goles', participantLabel: 'Equipo', matchLabel: 'Partido', tableLabel: 'Tabla', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, clock: true, overtime: true, bracket: true },
    presets: [{ slug: 'fifa-futsal', name: 'FIFA Futsal', formatSlug: 'groups-playoffs', rules: { minutesPerHalf: 20, accumulatedFouls: true } }],
  }),
  sport({
    name: 'Fútbol 7',
    slug: 'football-7',
    type: ['team'],
    participantCount: { min: 2, default: 7, max: 16, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'home-away'],
    scoring: { unit: 'goals', win: 3, draw: 1, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['points', 'goalDifference', 'goalsFor'] },
    matchStructure: { playersPerSide: 7, rosterMin: 5, rosterMax: 16, periods: 2, periodLabel: 'tiempo', periodMinutes: 25 },
    metrics: [...teamBallMetrics],
    ruleFields: [{ key: 'minutesPerHalf', label: 'Minutos por tiempo', type: 'number', defaultValue: 25, min: 10, max: 40 }],
    standings: { columns: ['PJ', 'G', 'E', 'P', 'GF', 'GC', 'DIF', 'PTS'], sort: ['points', 'goalDifference', 'goalsFor'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Goles', participantLabel: 'Equipo', matchLabel: 'Partido', tableLabel: 'Tabla', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, clock: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Fútbol 5',
    slug: 'football-5',
    type: ['team'],
    participantCount: { min: 2, default: 5, max: 12, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'home-away'],
    scoring: { unit: 'goals', win: 3, draw: 1, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['points', 'goalDifference', 'goalsFor'] },
    matchStructure: { playersPerSide: 5, rosterMin: 4, rosterMax: 12, periods: 2, periodLabel: 'tiempo', periodMinutes: 20 },
    metrics: [...teamBallMetrics],
    ruleFields: [{ key: 'minutesPerHalf', label: 'Minutos por tiempo', type: 'number', defaultValue: 20, min: 5, max: 35 }],
    standings: { columns: ['PJ', 'G', 'E', 'P', 'GF', 'GC', 'DIF', 'PTS'], sort: ['points', 'goalDifference', 'goalsFor'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Goles', participantLabel: 'Equipo', matchLabel: 'Partido', tableLabel: 'Tabla', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, clock: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Básquet',
    slug: 'basketball',
    type: ['team'],
    participantCount: { min: 2, default: 5, max: 15, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'conference', 'nba', 'bo3', 'bo5', 'bo7'],
    scoring: { unit: 'points', win: 2, loss: 0, allowsDraw: false, overtime: 'required', tieBreakers: ['wins', 'pointDifference', 'pointsFor', 'headToHead'] },
    matchStructure: { playersPerSide: 5, rosterMin: 5, rosterMax: 15, periods: 4, periodLabel: 'cuarto', periodMinutes: 10 },
    metrics: [...pointMetrics, { key: 'rebounds', label: 'Rebotes', type: 'number', scope: 'team' }, { key: 'assists', label: 'Asistencias', type: 'number', scope: 'team' }],
    ruleFields: [
      { key: 'quarters', label: 'Cuartos', type: 'number', defaultValue: 4, min: 2, max: 6 },
      { key: 'minutesPerQuarter', label: 'Minutos por cuarto', type: 'number', defaultValue: 10, min: 5, max: 12 },
      { key: 'shotClock', label: 'Reloj de posesión', type: 'number', defaultValue: 24, min: 12, max: 30 },
    ],
    standings: { columns: ['PJ', 'G', 'P', 'PF', 'PC', 'DIF', 'PTS'], sort: ['points', 'pointDifference', 'pointsFor'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Puntos', participantLabel: 'Equipo', matchLabel: 'Juego', tableLabel: 'Clasificación', fixtureLabel: 'Calendario' },
    supports: { groups: true, playoffs: true, series: true, clock: true, overtime: true, bracket: true },
    presets: [{ slug: 'nba-playoffs', name: 'NBA Playoffs', formatSlug: 'nba', rules: { quarters: 4, minutesPerQuarter: 12, seriesBestOf: 7 } }],
  }),
  sport({
    name: 'Tenis',
    slug: 'tennis',
    type: ['individual', 'doubles'],
    participantCount: { min: 2, default: 1, max: 2, label: 'Jugadores por lado' },
    validFormats: ['single-elimination', 'round-robin', 'groups-playoffs', 'atp', 'davis-cup', 'bo3', 'bo5'],
    scoring: { unit: 'sets', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['setsWon', 'gamesWon', 'headToHead'] },
    matchStructure: { playersPerSide: 1, sets: 3, gamesPerSet: 6 },
    metrics: [{ key: 'setsWon', label: 'Sets ganados', type: 'number', scope: 'participant' }, { key: 'gamesWon', label: 'Games ganados', type: 'number', scope: 'participant' }, { key: 'aces', label: 'Aces', type: 'number', scope: 'participant' }],
    ruleFields: [
      { key: 'bestOfSets', label: 'Mejor de sets', type: 'select', defaultValue: '3', options: ['1', '3', '5'] },
      { key: 'tieBreak', label: 'Tie-break', type: 'boolean', defaultValue: true },
      { key: 'superTieBreak', label: 'Super tie-break final', type: 'boolean', defaultValue: false },
    ],
    standings: { columns: ['PJ', 'G', 'P', 'SG', 'SP', 'GG', 'GP'], sort: ['wins', 'setsWon', 'gamesWon'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Sets', participantLabel: 'Jugador/Pareja', matchLabel: 'Partido', tableLabel: 'Ranking', fixtureLabel: 'Cuadro' },
    supports: { groups: true, playoffs: true, sets: true, series: true, ranking: true, bracket: true },
    presets: [{ slug: 'atp-250', name: 'ATP 250', formatSlug: 'atp', rules: { bestOfSets: '3', tieBreak: true, superTieBreak: false } }],
  }),
  sport({
    name: 'Pádel',
    slug: 'padel',
    type: ['doubles'],
    participantCount: { min: 2, default: 2, max: 2, label: 'Jugadores por pareja' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'bo3'],
    scoring: { unit: 'sets', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['setsWon', 'gamesWon', 'headToHead'] },
    matchStructure: { playersPerSide: 2, sets: 3, gamesPerSet: 6 },
    metrics: [{ key: 'setsWon', label: 'Sets ganados', type: 'number', scope: 'participant' }, { key: 'gamesWon', label: 'Games ganados', type: 'number', scope: 'participant' }],
    ruleFields: [
      { key: 'bestOfSets', label: 'Mejor de sets', type: 'select', defaultValue: '3', options: ['1', '3'] },
      { key: 'goldenPoint', label: 'Punto de oro', type: 'boolean', defaultValue: true },
    ],
    standings: { columns: ['PJ', 'G', 'P', 'SG', 'SP', 'GG', 'GP'], sort: ['wins', 'setsWon', 'gamesWon'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Sets', participantLabel: 'Pareja', matchLabel: 'Partido', tableLabel: 'Ranking', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, sets: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Vóley',
    slug: 'volleyball',
    type: ['team'],
    participantCount: { min: 2, default: 6, max: 14, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'olympic', 'bo3', 'bo5'],
    scoring: { unit: 'sets', win: 3, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['matchPoints', 'setsRatio', 'pointsRatio'] },
    matchStructure: { playersPerSide: 6, rosterMin: 6, rosterMax: 14, sets: 5 },
    metrics: [{ key: 'setsWon', label: 'Sets ganados', type: 'number', scope: 'team' }, { key: 'pointsWon', label: 'Puntos ganados', type: 'number', scope: 'team' }],
    ruleFields: [
      { key: 'bestOfSets', label: 'Mejor de sets', type: 'select', defaultValue: '5', options: ['3', '5'] },
      { key: 'pointsPerSet', label: 'Puntos por set', type: 'number', defaultValue: 25, min: 15, max: 30 },
      { key: 'tieBreakPoints', label: 'Puntos tie-break', type: 'number', defaultValue: 15, min: 7, max: 25 },
    ],
    standings: { columns: ['PJ', 'G', 'P', 'SG', 'SP', 'RATIO', 'PTS'], sort: ['points', 'setsRatio', 'pointsRatio'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Sets', participantLabel: 'Equipo', matchLabel: 'Partido', tableLabel: 'Tabla', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, sets: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Handball',
    slug: 'handball',
    type: ['team'],
    participantCount: { min: 2, default: 7, max: 16, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'olympic'],
    scoring: { unit: 'goals', win: 2, draw: 1, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['points', 'goalDifference', 'goalsFor'] },
    matchStructure: { playersPerSide: 7, rosterMin: 7, rosterMax: 16, periods: 2, periodLabel: 'tiempo', periodMinutes: 30 },
    metrics: [...teamBallMetrics, { key: 'saves', label: 'Atajadas', type: 'number', scope: 'team' }],
    ruleFields: [{ key: 'minutesPerHalf', label: 'Minutos por tiempo', type: 'number', defaultValue: 30, min: 10, max: 35 }],
    standings: { columns: ['PJ', 'G', 'E', 'P', 'GF', 'GC', 'DIF', 'PTS'], sort: ['points', 'goalDifference', 'goalsFor'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Goles', participantLabel: 'Equipo', matchLabel: 'Partido', tableLabel: 'Tabla', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, clock: true, overtime: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Hockey',
    slug: 'hockey',
    type: ['team'],
    participantCount: { min: 2, default: 11, max: 20, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'olympic'],
    scoring: { unit: 'goals', win: 3, draw: 1, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['points', 'goalDifference', 'goalsFor', 'shootouts'] },
    matchStructure: { playersPerSide: 11, rosterMin: 7, rosterMax: 20, periods: 4, periodLabel: 'cuarto', periodMinutes: 15 },
    metrics: [...teamBallMetrics, { key: 'corners', label: 'Córners cortos', type: 'number', scope: 'team' }],
    ruleFields: [{ key: 'quarters', label: 'Cuartos', type: 'number', defaultValue: 4, min: 2, max: 4 }],
    standings: { columns: ['PJ', 'G', 'E', 'P', 'GF', 'GC', 'DIF', 'PTS'], sort: ['points', 'goalDifference', 'goalsFor'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Goles', participantLabel: 'Equipo', matchLabel: 'Partido', tableLabel: 'Tabla', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, clock: true, overtime: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Rugby',
    slug: 'rugby',
    type: ['team'],
    participantCount: { min: 2, default: 15, max: 23, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'world-cup'],
    scoring: { unit: 'points', win: 4, draw: 2, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['points', 'pointDifference', 'triesFor', 'headToHead'] },
    matchStructure: { playersPerSide: 15, rosterMin: 15, rosterMax: 23, periods: 2, periodLabel: 'tiempo', periodMinutes: 40 },
    metrics: [...pointMetrics, { key: 'tries', label: 'Tries', type: 'number', scope: 'team' }],
    ruleFields: [
      { key: 'bonusTry', label: 'Bonus ofensivo', type: 'boolean', defaultValue: true },
      { key: 'bonusDefensive', label: 'Bonus defensivo', type: 'boolean', defaultValue: true },
    ],
    standings: { columns: ['PJ', 'G', 'E', 'P', 'TF', 'DIF', 'BP', 'PTS'], sort: ['points', 'pointDifference', 'tries'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Puntos', participantLabel: 'Equipo', matchLabel: 'Partido', tableLabel: 'Tabla', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, clock: true, overtime: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Béisbol',
    slug: 'baseball',
    type: ['team'],
    participantCount: { min: 2, default: 9, max: 26, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'conference', 'bo3', 'bo5', 'bo7'],
    scoring: { unit: 'runs', win: 1, loss: 0, allowsDraw: false, overtime: 'required', tieBreakers: ['wins', 'runDifferential', 'runsFor'] },
    matchStructure: { playersPerSide: 9, rosterMin: 9, rosterMax: 26, periods: 9, periodLabel: 'inning' },
    metrics: [{ key: 'runsFor', label: 'Carreras a favor', type: 'number', scope: 'team' }, { key: 'hits', label: 'Hits', type: 'number', scope: 'team' }, { key: 'errors', label: 'Errores', type: 'number', scope: 'team' }],
    ruleFields: [{ key: 'innings', label: 'Innings', type: 'number', defaultValue: 9, min: 3, max: 12 }],
    standings: { columns: ['PJ', 'G', 'P', 'RF', 'RA', 'DIF', 'PCT'], sort: ['winPercentage', 'runDifferential'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Carreras', participantLabel: 'Equipo', matchLabel: 'Juego', tableLabel: 'Standing', fixtureLabel: 'Calendario' },
    supports: { groups: true, playoffs: true, series: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Softball',
    slug: 'softball',
    type: ['team'],
    participantCount: { min: 2, default: 9, max: 20, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'double-elimination', 'bo3'],
    scoring: { unit: 'runs', win: 1, loss: 0, allowsDraw: false, overtime: 'required', tieBreakers: ['wins', 'runDifferential', 'runsFor'] },
    matchStructure: { playersPerSide: 9, rosterMin: 9, rosterMax: 20, periods: 7, periodLabel: 'inning' },
    metrics: [{ key: 'runsFor', label: 'Carreras a favor', type: 'number', scope: 'team' }, { key: 'hits', label: 'Hits', type: 'number', scope: 'team' }],
    ruleFields: [{ key: 'innings', label: 'Innings', type: 'number', defaultValue: 7, min: 3, max: 9 }],
    standings: { columns: ['PJ', 'G', 'P', 'RF', 'RA', 'DIF', 'PCT'], sort: ['winPercentage', 'runDifferential'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Carreras', participantLabel: 'Equipo', matchLabel: 'Juego', tableLabel: 'Standing', fixtureLabel: 'Calendario' },
    supports: { groups: true, playoffs: true, series: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Cricket',
    slug: 'cricket',
    type: ['team'],
    participantCount: { min: 2, default: 11, max: 16, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'groups-playoffs', 'single-elimination', 'world-cup'],
    scoring: { unit: 'runs', win: 2, draw: 1, loss: 0, allowsDraw: true, overtime: 'none', tieBreakers: ['points', 'netRunRate', 'runsFor'] },
    matchStructure: { playersPerSide: 11, rosterMin: 11, rosterMax: 16 },
    metrics: [{ key: 'runsFor', label: 'Runs a favor', type: 'number', scope: 'team' }, { key: 'wickets', label: 'Wickets', type: 'number', scope: 'team' }, { key: 'netRunRate', label: 'Net run rate', type: 'number', scope: 'team' }],
    ruleFields: [{ key: 'overs', label: 'Overs', type: 'number', defaultValue: 20, min: 5, max: 50 }],
    standings: { columns: ['PJ', 'G', 'E', 'P', 'NRR', 'PTS'], sort: ['points', 'netRunRate'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Runs', participantLabel: 'Equipo', matchLabel: 'Match', tableLabel: 'Table', fixtureLabel: 'Fixtures' },
    supports: { groups: true, playoffs: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Tenis de mesa',
    slug: 'table-tennis',
    type: ['individual', 'doubles', 'team'],
    participantCount: { min: 2, default: 1, max: 2, label: 'Jugadores por lado' },
    validFormats: ['single-elimination', 'double-elimination', 'round-robin', 'groups-playoffs', 'bo3', 'bo5', 'bo7'],
    scoring: { unit: 'sets', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['setsWon', 'pointsWon'] },
    matchStructure: { sets: 5 },
    metrics: [{ key: 'setsWon', label: 'Sets ganados', type: 'number', scope: 'participant' }, { key: 'pointsWon', label: 'Puntos ganados', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'bestOfSets', label: 'Mejor de sets', type: 'select', defaultValue: '5', options: ['3', '5', '7'] }],
    standings: { columns: ['PJ', 'G', 'P', 'SG', 'SP'], sort: ['wins', 'setsWon'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Sets', participantLabel: 'Jugador/Pareja', matchLabel: 'Partido', tableLabel: 'Ranking', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, sets: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Badminton',
    slug: 'badminton',
    type: ['individual', 'doubles', 'team'],
    participantCount: { min: 2, default: 1, max: 2, label: 'Jugadores por lado' },
    validFormats: ['single-elimination', 'round-robin', 'groups-playoffs', 'olympic', 'bo3'],
    scoring: { unit: 'sets', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['setsWon', 'pointsWon'] },
    matchStructure: { sets: 3 },
    metrics: [{ key: 'setsWon', label: 'Sets ganados', type: 'number', scope: 'participant' }, { key: 'pointsWon', label: 'Puntos ganados', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'pointsPerSet', label: 'Puntos por set', type: 'number', defaultValue: 21, min: 11, max: 30 }],
    standings: { columns: ['PJ', 'G', 'P', 'SG', 'SP'], sort: ['wins', 'setsWon'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Sets', participantLabel: 'Jugador/Pareja', matchLabel: 'Partido', tableLabel: 'Ranking', fixtureLabel: 'Fixture' },
    supports: { groups: true, playoffs: true, sets: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'MMA',
    slug: 'mma',
    type: ['individual'],
    participantCount: { min: 2, default: 1, max: 1, label: 'Peleadores por lado' },
    validFormats: ['single-elimination', 'ufc', 'ladder'],
    scoring: { unit: 'rounds', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['finish', 'decision'] },
    matchStructure: { rounds: 3, roundMinutes: 5 },
    metrics: [{ key: 'method', label: 'Método', type: 'text', scope: 'match' }, { key: 'significantStrikes', label: 'Golpes significativos', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'rounds', label: 'Rounds', type: 'select', defaultValue: '3', options: ['3', '5'] }],
    standings: { columns: ['Peleador', 'G', 'P', 'Finalizaciones'], sort: ['wins', 'finishes'], supportsRanking: true, supportsClassification: false },
    ui: { primaryScoreLabel: 'Resultado', participantLabel: 'Peleador', matchLabel: 'Combate', tableLabel: 'Ranking', fixtureLabel: 'Cartelera' },
    supports: { rounds: true, bracket: true },
    presets: [{ slug: 'ufc-main-card', name: 'UFC Main Card', formatSlug: 'ufc', rules: { rounds: '3', championshipRounds: 5 } }],
  }),
  sport({
    name: 'Boxeo',
    slug: 'boxing',
    type: ['individual'],
    participantCount: { min: 2, default: 1, max: 1, label: 'Boxeadores por lado' },
    validFormats: ['single-elimination', 'ladder', 'olympic'],
    scoring: { unit: 'judges', win: 1, loss: 0, allowsDraw: true, overtime: 'none', tieBreakers: ['decision', 'knockdowns'] },
    matchStructure: { rounds: 12, roundMinutes: 3 },
    metrics: [{ key: 'knockdowns', label: 'Caídas', type: 'number', scope: 'participant' }, { key: 'judgeCards', label: 'Tarjetas', type: 'text', scope: 'match' }],
    ruleFields: [{ key: 'rounds', label: 'Rounds', type: 'number', defaultValue: 12, min: 3, max: 12 }],
    standings: { columns: ['Boxeador', 'G', 'P', 'E', 'KO'], sort: ['wins', 'kos'], supportsRanking: true, supportsClassification: false },
    ui: { primaryScoreLabel: 'Decisión', participantLabel: 'Boxeador', matchLabel: 'Pelea', tableLabel: 'Ranking', fixtureLabel: 'Cartelera' },
    supports: { rounds: true },
    presets: [],
  }),
  sport({
    name: 'Ajedrez',
    slug: 'chess',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 8, label: 'Jugadores por lado' },
    validFormats: ['swiss', 'round-robin', 'single-elimination', 'ladder', 'arena'],
    scoring: { unit: 'points', win: 1, draw: 0.5, loss: 0, allowsDraw: true, overtime: 'none', tieBreakers: ['buchholz', 'sonnebornBerger', 'directEncounter', 'wins'] },
    matchStructure: {},
    metrics: [{ key: 'rating', label: 'Rating', type: 'number', scope: 'participant' }, { key: 'buchholz', label: 'Buchholz', type: 'number', scope: 'participant' }],
    ruleFields: [
      { key: 'timeControl', label: 'Ritmo', type: 'select', defaultValue: 'rapid', options: ['bullet', 'blitz', 'rapid', 'classical'] },
      { key: 'incrementSeconds', label: 'Incremento', type: 'number', defaultValue: 0, min: 0, max: 60 },
    ],
    standings: { columns: ['PJ', 'G', 'E', 'P', 'Buchholz', 'PTS'], sort: ['points', 'buchholz', 'wins'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Puntos', participantLabel: 'Jugador', matchLabel: 'Partida', tableLabel: 'Tabla', fixtureLabel: 'Rondas' },
    supports: { ranking: true, tieBreakers: true, clock: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Esports',
    slug: 'esports',
    type: ['individual', 'team', 'mixed'],
    participantCount: { min: 2, default: 5, max: 10, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'single-elimination', 'double-elimination', 'groups-playoffs', 'swiss', 'worlds', 'bo1', 'bo3', 'bo5', 'battle-royale', 'arena'],
    scoring: { unit: 'maps', win: 3, draw: 1, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['matchWins', 'mapDifference', 'roundDifference', 'headToHead'] },
    matchStructure: { maps: 1 },
    metrics: [{ key: 'mapsWon', label: 'Mapas ganados', type: 'number', scope: 'team' }, { key: 'kills', label: 'Kills', type: 'number', scope: 'team' }, { key: 'placement', label: 'Posición', type: 'number', scope: 'team' }],
    ruleFields: [
      { key: 'bestOf', label: 'Best of', type: 'select', defaultValue: '1', options: ['1', '3', '5', '7'] },
      { key: 'gameTitle', label: 'Juego', type: 'text', defaultValue: '' },
    ],
    standings: { columns: ['PJ', 'G', 'P', 'MG', 'MP', 'DIF', 'PTS'], sort: ['points', 'mapDifference', 'roundDifference'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Mapas', participantLabel: 'Equipo/Jugador', matchLabel: 'Match', tableLabel: 'Standings', fixtureLabel: 'Schedule' },
    supports: { groups: true, playoffs: true, series: true, ranking: true, bracket: true },
    presets: [{ slug: 'worlds', name: 'Worlds', formatSlug: 'worlds', rules: { bestOf: '3', swissStage: true } }],
  }),
  sport({
    name: 'Fórmula 1 / Automovilismo',
    slug: 'motorsport',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 4, label: 'Pilotos por equipo' },
    validFormats: ['points-classification', 'time-trial', 'stages'],
    scoring: { unit: 'placement', win: 25, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['wins', 'podiums', 'bestFinish'] },
    matchStructure: {},
    metrics: [{ key: 'time', label: 'Tiempo', type: 'duration', scope: 'participant' }, { key: 'laps', label: 'Vueltas', type: 'number', scope: 'event' }, { key: 'position', label: 'Posición', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'pointsSystem', label: 'Sistema de puntos', type: 'select', defaultValue: 'f1', options: ['f1', 'custom', 'linear'] }],
    standings: { columns: ['Piloto', 'Carreras', 'Victorias', 'Podios', 'PTS'], sort: ['points', 'wins', 'podiums'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Posición', participantLabel: 'Piloto/Equipo', matchLabel: 'Carrera', tableLabel: 'Campeonato', fixtureLabel: 'Calendario' },
    supports: { classification: true, ranking: true },
    presets: [],
  }),
  sport({
    name: 'Ciclismo',
    slug: 'cycling',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 12, label: 'Ciclistas por equipo' },
    validFormats: ['time-trial', 'points-classification', 'stages', 'heats'],
    scoring: { unit: 'time', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['totalTime', 'stageWins', 'points'] },
    matchStructure: {},
    metrics: [{ key: 'time', label: 'Tiempo', type: 'duration', scope: 'participant' }, { key: 'distance', label: 'Distancia', type: 'number', scope: 'event' }, { key: 'stageWins', label: 'Etapas ganadas', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'classificationType', label: 'Clasificación', type: 'select', defaultValue: 'general', options: ['general', 'points', 'mountain', 'team'] }],
    standings: { columns: ['Participante', 'Tiempo', 'Etapas', 'PTS'], sort: ['totalTime', 'points'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Tiempo', participantLabel: 'Ciclista/Equipo', matchLabel: 'Etapa', tableLabel: 'Clasificación', fixtureLabel: 'Etapas' },
    supports: { classification: true, heats: true },
    presets: [],
  }),
  sport({
    name: 'Running',
    slug: 'running',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 12, label: 'Corredores por equipo' },
    validFormats: ['time-trial', 'points-classification', 'heats', 'olympic'],
    scoring: { unit: 'time', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['time', 'bestMark'] },
    matchStructure: { heatSize: 8 },
    metrics: [{ key: 'time', label: 'Tiempo', type: 'duration', scope: 'participant' }, { key: 'pace', label: 'Ritmo', type: 'duration', scope: 'participant' }],
    ruleFields: [{ key: 'distanceMeters', label: 'Distancia (m)', type: 'number', defaultValue: 5000, min: 60, max: 42195 }],
    standings: { columns: ['Atleta', 'Marca', 'Serie', 'Pos'], sort: ['time'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Tiempo', participantLabel: 'Atleta', matchLabel: 'Carrera', tableLabel: 'Clasificación', fixtureLabel: 'Series' },
    supports: { heats: true, classification: true },
    presets: [],
  }),
  sport({
    name: 'Natación',
    slug: 'swimming',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 4, label: 'Nadadores por equipo' },
    validFormats: ['heats', 'time-trial', 'olympic', 'points-classification'],
    scoring: { unit: 'time', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['time', 'reactionTime'] },
    matchStructure: { heatSize: 8 },
    metrics: [{ key: 'time', label: 'Tiempo', type: 'duration', scope: 'participant' }, { key: 'reactionTime', label: 'Reacción', type: 'duration', scope: 'participant' }],
    ruleFields: [{ key: 'distanceMeters', label: 'Distancia (m)', type: 'select', defaultValue: '100', options: ['50', '100', '200', '400', '800', '1500'] }],
    standings: { columns: ['Nadador', 'Marca', 'Serie', 'Pos'], sort: ['time'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Tiempo', participantLabel: 'Nadador/Equipo', matchLabel: 'Prueba', tableLabel: 'Clasificación', fixtureLabel: 'Series' },
    supports: { heats: true, classification: true },
    presets: [],
  }),
  sport({
    name: 'Atletismo',
    slug: 'athletics',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 4, label: 'Atletas por equipo' },
    validFormats: ['heats', 'time-trial', 'points-classification', 'olympic'],
    scoring: { unit: 'time', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['mark', 'bestAttempt'] },
    matchStructure: { attempts: 6, heatSize: 8 },
    metrics: [{ key: 'mark', label: 'Marca', type: 'number', scope: 'participant' }, { key: 'time', label: 'Tiempo', type: 'duration', scope: 'participant' }],
    ruleFields: [{ key: 'eventType', label: 'Tipo de prueba', type: 'select', defaultValue: 'track', options: ['track', 'field', 'combined'] }],
    standings: { columns: ['Atleta', 'Marca', 'Intentos', 'Pos'], sort: ['mark', 'time'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Marca', participantLabel: 'Atleta', matchLabel: 'Prueba', tableLabel: 'Clasificación', fixtureLabel: 'Series' },
    supports: { heats: true, classification: true },
    presets: [],
  }),
  sport({
    name: 'Surf',
    slug: 'surf',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 4, label: 'Surfistas por equipo' },
    validFormats: ['heats', 'single-elimination', 'points-classification'],
    scoring: { unit: 'judges', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['bestWave', 'secondBestWave'] },
    matchStructure: { heatSize: 4 },
    metrics: [{ key: 'bestWave', label: 'Mejor ola', type: 'number', scope: 'participant' }, { key: 'heatTotal', label: 'Total heat', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'wavesCounted', label: 'Olas que puntúan', type: 'number', defaultValue: 2, min: 1, max: 5 }],
    standings: { columns: ['Surfista', 'Heat', 'Mejor ola', 'Total'], sort: ['heatTotal', 'bestWave'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Puntaje', participantLabel: 'Surfista', matchLabel: 'Heat', tableLabel: 'Clasificación', fixtureLabel: 'Heats' },
    supports: { heats: true, classification: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Skate',
    slug: 'skate',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 4, label: 'Skaters por equipo' },
    validFormats: ['points-classification', 'heats', 'olympic'],
    scoring: { unit: 'judges', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['bestRun', 'bestTrick'] },
    matchStructure: { attempts: 5 },
    metrics: [{ key: 'bestRun', label: 'Mejor ronda', type: 'number', scope: 'participant' }, { key: 'bestTrick', label: 'Mejor truco', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'attempts', label: 'Intentos', type: 'number', defaultValue: 5, min: 2, max: 8 }],
    standings: { columns: ['Skater', 'Run', 'Trick', 'Total'], sort: ['total', 'bestRun'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Puntaje', participantLabel: 'Skater', matchLabel: 'Ronda', tableLabel: 'Clasificación', fixtureLabel: 'Rondas' },
    supports: { classification: true },
    presets: [],
  }),
  sport({
    name: 'Golf',
    slug: 'golf',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 4, label: 'Golfistas por equipo' },
    validFormats: ['points-classification', 'stages', 'round-robin', 'single-elimination'],
    scoring: { unit: 'strokes', win: 1, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['strokes', 'playoffHole'] },
    matchStructure: { holes: 18 },
    metrics: [{ key: 'strokes', label: 'Golpes', type: 'number', scope: 'participant' }, { key: 'par', label: 'Par', type: 'number', scope: 'event' }],
    ruleFields: [{ key: 'holes', label: 'Hoyos', type: 'select', defaultValue: '18', options: ['9', '18', '36', '72'] }],
    standings: { columns: ['Jugador', 'Rondas', 'Par', 'Golpes'], sort: ['strokes'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Golpes', participantLabel: 'Jugador', matchLabel: 'Ronda', tableLabel: 'Leaderboard', fixtureLabel: 'Salidas' },
    supports: { classification: true, overtime: true },
    presets: [],
  }),
  sport({
    name: 'Bowling',
    slug: 'bowling',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 5, label: 'Jugadores por equipo' },
    validFormats: ['league', 'round-robin', 'single-elimination', 'points-classification'],
    scoring: { unit: 'pins', win: 1, loss: 0, allowsDraw: true, overtime: 'optional', tieBreakers: ['pins', 'highGame'] },
    matchStructure: {},
    metrics: [{ key: 'pins', label: 'Pinos', type: 'number', scope: 'participant' }, { key: 'strikes', label: 'Strikes', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'gamesPerSeries', label: 'Juegos por serie', type: 'number', defaultValue: 3, min: 1, max: 6 }],
    standings: { columns: ['PJ', 'G', 'P', 'Pinos', 'Promedio'], sort: ['wins', 'pins'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Pinos', participantLabel: 'Jugador/Equipo', matchLabel: 'Serie', tableLabel: 'Tabla', fixtureLabel: 'Fixture' },
    supports: { classification: true, bracket: true },
    presets: [],
  }),
  sport({
    name: 'Artes marciales',
    slug: 'martial-arts',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 5, label: 'Competidores por lado' },
    validFormats: ['single-elimination', 'double-elimination', 'round-robin', 'olympic', 'points-classification'],
    scoring: { unit: 'points', win: 1, loss: 0, allowsDraw: false, overtime: 'optional', tieBreakers: ['points', 'penalties', 'warnings'] },
    matchStructure: { rounds: 3, roundMinutes: 2 },
    metrics: [{ key: 'pointsFor', label: 'Puntos', type: 'number', scope: 'participant' }, { key: 'penalties', label: 'Penalizaciones', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'discipline', label: 'Disciplina', type: 'select', defaultValue: 'karate', options: ['karate', 'taekwondo', 'judo', 'jiu-jitsu'] }],
    standings: { columns: ['Competidor', 'G', 'P', 'Puntos'], sort: ['wins', 'points'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Puntos', participantLabel: 'Competidor', matchLabel: 'Combate', tableLabel: 'Clasificación', fixtureLabel: 'Llaves' },
    supports: { rounds: true, bracket: true, classification: true },
    presets: [],
  }),
  sport({
    name: 'Levantamiento olímpico',
    slug: 'olympic-weightlifting',
    type: ['individual', 'team'],
    participantCount: { min: 2, default: 1, max: 4, label: 'Atletas por equipo' },
    validFormats: ['points-classification', 'olympic'],
    scoring: { unit: 'weight', win: 1, loss: 0, allowsDraw: false, overtime: 'none', tieBreakers: ['bodyWeight', 'bestLift'] },
    matchStructure: { attempts: 6 },
    metrics: [{ key: 'snatch', label: 'Arranque', type: 'number', scope: 'participant' }, { key: 'cleanJerk', label: 'Envión', type: 'number', scope: 'participant' }, { key: 'total', label: 'Total', type: 'number', scope: 'participant' }],
    ruleFields: [{ key: 'attemptsPerLift', label: 'Intentos por levantamiento', type: 'number', defaultValue: 3, min: 1, max: 4 }],
    standings: { columns: ['Atleta', 'Arranque', 'Envión', 'Total'], sort: ['total', 'bodyWeight'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Kg', participantLabel: 'Atleta', matchLabel: 'Grupo', tableLabel: 'Clasificación', fixtureLabel: 'Tandas' },
    supports: { classification: true },
    presets: [],
  }),
  sport({
    name: 'CrossFit',
    slug: 'crossfit',
    type: ['individual', 'team', 'mixed'],
    participantCount: { min: 2, default: 1, max: 6, label: 'Atletas por equipo' },
    validFormats: ['crossfit', 'points-classification', 'heats', 'stages'],
    scoring: { unit: 'points', win: 100, loss: 0, allowsDraw: true, overtime: 'none', tieBreakers: ['eventWins', 'bestPlacement'] },
    matchStructure: { heatSize: 12 },
    metrics: [{ key: 'reps', label: 'Reps', type: 'number', scope: 'participant' }, { key: 'time', label: 'Tiempo', type: 'duration', scope: 'participant' }, { key: 'load', label: 'Carga', type: 'number', scope: 'participant' }],
    ruleFields: [
      { key: 'events', label: 'Eventos', type: 'number', defaultValue: 5, min: 1, max: 15 },
      { key: 'scoringMode', label: 'Scoring', type: 'select', defaultValue: 'placement', options: ['placement', 'points-table', 'custom'] },
    ],
    standings: { columns: ['Atleta', 'Eventos', 'Victorias', 'PTS'], sort: ['points', 'eventWins', 'bestPlacement'], supportsRanking: true, supportsClassification: true },
    ui: { primaryScoreLabel: 'Puntos', participantLabel: 'Atleta/Equipo', matchLabel: 'Evento', tableLabel: 'Leaderboard', fixtureLabel: 'Heats' },
    supports: { heats: true, classification: true, ranking: true },
    presets: [{ slug: 'games-style', name: 'CrossFit Games', formatSlug: 'crossfit', rules: { events: 8, scoringMode: 'placement' } }],
  }),
]

export const SPORTS_BY_SLUG = Object.fromEntries(SPORTS.map((sport) => [sport.slug, sport])) as Record<string, SportDefinition>

export function getSportBySlug(slug: string) {
  return SPORTS_BY_SLUG[slug]
}

export function getFormatBySlug(slug: string) {
  return COMPETITION_FORMATS[slug as CompetitionFormatSlug]
}

export function getFormatsForSport(sportSlug: string) {
  const sportDefinition = getSportBySlug(sportSlug)
  if (!sportDefinition) return []
  return sportDefinition.validFormats.map((formatSlug) => COMPETITION_FORMATS[formatSlug]).filter(Boolean)
}
