import { FeatureKey, PlanDefinition, PlanSlug } from './types'

const UNLIMITED = -1

export const PLANS: Record<PlanSlug, PlanDefinition> = {
  free: {
    slug: 'free',
    name: 'Free',
    description: 'Captación gratuita para ligas pequeñas y pruebas rápidas.',
    priceMonthly: 0,
    priceAnnual: 0,
    isFree: true,
    isEnterprise: false,
    features: [FeatureKey.BASIC_STATS, FeatureKey.PUBLIC_PAGE],
    limits: {
      activeTournaments: 1,
      teams: 8,
      players: 50,
      organizations: 1,
      users: 5,
      storageMb: 500,
      apiCallsPerMonth: 1000,
      customDomains: 0,
      whiteLabelSeats: 0,
    },
    defaultAddons: [],
  },
  starter: {
    slug: 'starter',
    name: 'Starter',
    description: 'Organizadores pequeños con múltiples torneos y equipos ilimitados.',
    priceMonthly: 990,
    priceAnnual: 9900,
    isFree: false,
    isEnterprise: false,
    features: [FeatureKey.BASIC_STATS, FeatureKey.PUBLIC_PAGE, FeatureKey.MULTI_SPORTS],
    limits: {
      activeTournaments: UNLIMITED,
      teams: UNLIMITED,
      players: UNLIMITED,
      organizations: 1,
      users: 25,
      storageMb: 5000,
      apiCallsPerMonth: 10000,
      customDomains: 0,
      whiteLabelSeats: 0,
    },
    defaultAddons: [],
  },
  pro: {
    slug: 'pro',
    name: 'Pro',
    description: 'Ligas con estadísticas avanzadas, planteles y soporte multi-deporte.',
    priceMonthly: 2490,
    priceAnnual: 24900,
    isFree: false,
    isEnterprise: false,
    features: [
      FeatureKey.ADVANCED_STATS,
      FeatureKey.PLAYER_PROFILES,
      FeatureKey.ASSISTS,
      FeatureKey.GOALSCORERS,
      FeatureKey.MULTI_SPORTS,
      FeatureKey.SEASONS,
      FeatureKey.HISTORY,
      FeatureKey.PUBLIC_PAGE,
    ],
    limits: {
      activeTournaments: UNLIMITED,
      teams: UNLIMITED,
      players: UNLIMITED,
      organizations: 1,
      users: 100,
      storageMb: 15000,
      apiCallsPerMonth: 50000,
      customDomains: 1,
      whiteLabelSeats: 0,
    },
    defaultAddons: ['PREMIUM_STATS'],
  },
  liga: {
    slug: 'liga',
    name: 'Liga',
    description: 'Organizaciones grandes con temporadas, dominios propios y branding avanzado.',
    priceMonthly: 4990,
    priceAnnual: 49900,
    isFree: false,
    isEnterprise: false,
    features: [
      FeatureKey.ADVANCED_STATS,
      FeatureKey.PLAYER_PROFILES,
      FeatureKey.ASSISTS,
      FeatureKey.GOALSCORERS,
      FeatureKey.MULTI_SPORTS,
      FeatureKey.SEASONS,
      FeatureKey.HISTORY,
      FeatureKey.PUBLIC_PAGE,
      FeatureKey.CUSTOM_DOMAIN,
      FeatureKey.PRIORITY_SUPPORT,
    ],
    limits: {
      activeTournaments: UNLIMITED,
      teams: UNLIMITED,
      players: UNLIMITED,
      organizations: UNLIMITED,
      users: 250,
      storageMb: 50000,
      apiCallsPerMonth: 200000,
      customDomains: 3,
      whiteLabelSeats: 0,
    },
    defaultAddons: ['CUSTOM_DOMAIN'],
  },
  federacion: {
    slug: 'federacion',
    name: 'Federación',
    description: 'Federaciones y asociaciones con white label, API y soporte prioritario.',
    priceMonthly: 9990,
    priceAnnual: 99900,
    isFree: false,
    isEnterprise: true,
    features: [
      FeatureKey.ADVANCED_STATS,
      FeatureKey.PLAYER_PROFILES,
      FeatureKey.ASSISTS,
      FeatureKey.GOALSCORERS,
      FeatureKey.MULTI_SPORTS,
      FeatureKey.SEASONS,
      FeatureKey.HISTORY,
      FeatureKey.PUBLIC_PAGE,
      FeatureKey.CUSTOM_DOMAIN,
      FeatureKey.WHITE_LABEL,
      FeatureKey.API_ACCESS,
      FeatureKey.MULTI_ORG,
      FeatureKey.PRIORITY_SUPPORT,
      FeatureKey.MOBILE_APP,
    ],
    limits: {
      activeTournaments: UNLIMITED,
      teams: UNLIMITED,
      players: UNLIMITED,
      organizations: UNLIMITED,
      users: UNLIMITED,
      storageMb: 200000,
      apiCallsPerMonth: 1000000,
      customDomains: 10,
      whiteLabelSeats: 1,
    },
    defaultAddons: ['WHITE_LABEL', 'API_ADVANCED'],
  },
}

export function getPlanDefinition(slug: PlanSlug) {
  return PLANS[slug]
}

export const AVAILABLE_FEATURES: Record<FeatureKey, string> = {
  [FeatureKey.BASIC_STATS]: 'Estadísticas básicas',
  [FeatureKey.ADVANCED_STATS]: 'Estadísticas avanzadas',
  [FeatureKey.PLAYER_PROFILES]: 'Perfiles de jugadores',
  [FeatureKey.ASSISTS]: 'Registro de asistencias',
  [FeatureKey.GOALSCORERS]: 'Tabla de goleadores',
  [FeatureKey.LIVE_EVENTS]: 'Eventos en vivo',
  [FeatureKey.CUSTOM_DOMAIN]: 'Dominio personalizado',
  [FeatureKey.WHITE_LABEL]: 'White label',
  [FeatureKey.API_ACCESS]: 'Acceso a API',
  [FeatureKey.MULTI_ORG]: 'Múltiples organizaciones',
  [FeatureKey.MOBILE_APP]: 'App móvil futura',
  [FeatureKey.PUBLIC_PAGE]: 'Sitio público',
  [FeatureKey.SEASONS]: 'Temporadas',
  [FeatureKey.HISTORY]: 'Historial',
  [FeatureKey.PRIORITY_SUPPORT]: 'Soporte prioritario',
  [FeatureKey.STREAMING]: 'Streaming',
  [FeatureKey.ONLINE_REGISTRATION]: 'Inscripciones online',
  [FeatureKey.FINANCE_MANAGEMENT]: 'Gestión económica',
  [FeatureKey.MULTI_SPORTS]: 'Múltiples deportes',
}
